name: census-population-api

services:
  database:
    image: postgres:latest
    volumes:
      - database:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DB_USERNAME} -d ${DB_NAME}" ]
      interval: 30s
      timeout: 10s
      retries: 5

  redis:
    image: redis:latest
    volumes:
      - redis:/data
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 30s
      timeout: 10s
      retries: 5

  api:
    image: ghcr.io/census-population-project/api:0.1.0
    ports:
      - "38472:3000"
    volumes:
      - ./private.key:/app/private.key:ro
      - ./public.key:/app/public.key:ro
    restart: always
    env_file:
      - .env
    depends_on:
      database:
        condition: service_healthy
      redis:
        condition: service_healthy

volumes:
  database:
  redis: